services:
  postgres_sale:
    image: postgres
    hostname: postgres-sale
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=sale
      - POSTGRES_PASSWORD=sale123
    volumes:
      - app-db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    restart: always
    volumes:
      - minio_storage:/data

volumes:
  app-db-data:
  minio_storage: