# put your configuration values here

[runtime]
log_level="WARNING"  # the system log level of dlt
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/reference/telemetry
dlthub_telemetry = true

# Configuração do destino filesystem
[destination.filesystem]
bucket_url = "s3://landing"

# Desabilita compressão para garantir arquivos CSV não zipados
[normalize.data_writer]
disable_compression = true

[loader.data_writer]
disable_compression = true
